### ISSUE TITLE
Result layers not added to the viewer in napari 0.5.0

### ISSUE THREAD

**Issue by AlbertDominguez** [stardist/stardist-napari#26]
**Describe the bug**
Despite the network running successfully, resulting layers are not added to the viewer after updating napari to `0.5.0`.

I Had the same issue in `napari-spotiflow`, which I temporarily (and uglily 🙂) fixed by updating the viewer object itself instead of returning the new layers (see https://github.com/weigertlab/napari-spotiflow/compare/272ec57...01d0949). Applying the same fix here is not so direct (I think) given the usage of futures.

**To reproduce**
1. From the console:
   ```console
    napari --with stardist-napari
    ```
2. File -> Open sample -> stardist-napari -> Nuclei (2D)
3. Run prediction normally with the `Versatile (fluorescent nuclei)` model

**Expected behavior**
Layers with polygons and labels of the prediction should be added to the viewer. 

**Environment:**

1. napari-info:
```
napari: 0.5.0
Platform: macOS-14.3-arm64-arm-64bit
System: MacOS 14.3
Python: 3.10.14 (main, May 6 2024, 14:42:37) [Clang 14.0.6 ]
Qt: 5.15.14
PyQt5: 5.15.11
NumPy: 1.26.4
SciPy: 1.14.0
Dask: 2024.7.1
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.6

OpenGL:
- GL version: 2.1 Metal - 88
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 1512x982, scale 2.0
- screen 2: resolution 2560x1440, scale 1.0

Optional:
- numba: 0.60.0
- triangle not installed

Settings path:
- /Users/adomi/Library/Application Support/napari/napari-upd_6108c6ce5e55a194c9830f578916bfbe969266d9/settings.yaml
```

2. OS/libs info:
```
os: macOS-14.3-arm64-arm-64bit
stardist_napari: 2022.12.6
stardist: 0.9.1
csbdeep: 0.8.0
napari: 0.5.0
magicgui: 0.8.3
tensorflow: 2.16.2
```

**Comment by psobolewskiPhD** [comment]
Good news!
@DragaDoncila spelunked her way to the change!
Basically in 0.5.0 napari dropped python 3.8 support and changed from using `typing.List` to just `list`, but apparently when registered with magicgui they are not equivalent.
https://github.com/napari/napari/issues/7129

So going forward, on the napari side we band-aid and register `List` and `list` https://github.com/napari/napari/pull/7130 -- we are releasing pretty quickly so that would get the fix out with no changes in this plugin required for anyone else that has used `List(LayerDataTuple)`
We are looking into how upstream magicgui handles it, a fix there would be same result as above.

But here in this plugin, could drop python 3.8 and switch to `list` and make a release, which would work immediately.

**Comment by AlbertDominguez** [comment]
Oh great, thanks a lot for taking a look and the fix on the napari side @psobolewskiPhD and @DragaDoncila! Not closing for now in case Uwe wants to do the aforementioned changes :)

**Comment by maweigert** [comment]
just released a new version on pypi, could you try whether that fixes the issue?

`pip install -U --no-deps stardist-napari`

**Comment by AlbertDominguez** [comment]
Works for me now!

**Comment by psobolewskiPhD** [comment]
Yup! the new release works. Thanks @maweigert and sorry about that!
Note that the problem is partially solved upstream in magicgui now:
https://github.com/pyapp-kit/magicgui/pull/658 has been released
Just the Future part still needs fixing:
https://github.com/pyapp-kit/magicgui/pull/665
